#!/usr/bin/env python3
"""
Platinum Tier - Cloud Agent
Always-on cloud agent with A2A protocol integration
Handles: Email triage, draft replies, social post drafts, draft accounting actions
"""

import os
import sys
import json
import logging
import time
from datetime import datetime
from threading import Thread
import signal

# Add scripts directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from a2a_orchestrator import A2AOrchestrator

# Configure logging
log_dir = os.path.join(os.path.dirname(__file__), '..', 'Logs')
os.makedirs(log_dir, exist_ok=True)

log_file = os.path.join(log_dir, f'platinum_cloud_{datetime.now().strftime("%Y%m%d")}.log')

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class PlatinumCloudAgent:
    """
    Platinum Tier Cloud Agent
    Always-on agent running in cloud VM
    """

    def __init__(self, vault_path: str):
        """
        Initialize Platinum Cloud Agent

        Args:
            vault_path: Path to AI Employee Vault (synced via Git)
        """
        self.vault_path = vault_path
        self.running = False
        self.watchers = []
        self.a2a = None

        logger.info("=" * 80)
        logger.info("Platinum Tier Cloud Agent Initializing")
        logger.info("=" * 80)

    def _load_config(self):
        """Load cloud configuration"""
        config_path = os.path.join(self.vault_path, 'golden_tier_config.json')

        if os.path.exists(config_path):
            with open(config_path, 'r') as f:
                return json.load(f)
        else:
            logger.warning("Config file not found, using defaults")
            return {}

    def _start_watchers(self):
        """Start cloud-owned watchers"""
        logger.info("Starting cloud watchers...")

        # Import watchers
        try:
            from gmail_watcher import GmailWatcher

            # Start Gmail watcher for email triage
            gmail_watcher = GmailWatcher(self.vault_path)
            gmail_thread = Thread(target=gmail_watcher.start, daemon=True)
            gmail_thread.start()
            self.watchers.append(('gmail', gmail_thread))
            logger.info("✓ Gmail watcher started (email triage)")

        except Exception as e:
            logger.error(f"Failed to start Gmail watcher: {e}")

        # TODO: Add social media watchers for monitoring
        # TODO: Add file system watcher for /Needs_Action/cloud/

        logger.info(f"Started {len(self.watchers)} watchers")

    def _start_a2a(self):
        """Start A2A protocol orchestrator"""
        logger.info("Starting A2A orchestrator...")

        try:
            self.a2a = A2AOrchestrator('cloud', self.vault_path)
            self.a2a.start()
            logger.info("✓ A2A orchestrator started")
        except Exception as e:
            logger.error(f"Failed to start A2A orchestrator: {e}")
            self.a2a = None

    def _process_email_triage(self):
        """
        Process emails and create draft replies
        Cloud responsibility: Draft only, requires Local approval
        """
        needs_action_path = os.path.join(self.vault_path, 'Needs_Action', 'cloud')

        if not os.path.exists(needs_action_path):
            return

        for filename in os.listdir(needs_action_path):
            if not filename.endswith('.md'):
                continue

            try:
                filepath = os.path.join(needs_action_path, filename)

                # Read email task
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()

                # Check if it's an email that needs a reply
                if 'email' not in filename.lower():
                    continue

                logger.info(f"Processing email task: {filename}")

                # TODO: Use Claude/LLM to draft reply
                # For now, create a simple draft

                draft_reply = {
                    'to': 'recipient@example.com',  # Extract from email
                    'subject': 'Re: Email Subject',
                    'body': 'Draft reply generated by Cloud Agent.\n\nThis is a placeholder draft.'
                }

                # Create approval request
                approval_id = filename.replace('.md', '_approval')

                approval_action = {
                    'action_type': 'send_email',
                    'description': f'Send draft email reply',
                    'draft_data': draft_reply,
                    'risk_level': 'low',
                    'estimated_impact': 'Responds to incoming email'
                }

                # Send approval request via A2A
                if self.a2a:
                    success = self.a2a.request_approval(approval_action, approval_id)

                    if success:
                        logger.info(f"✓ Approval request sent via A2A: {approval_id}")

                        # Move to In_Progress
                        in_progress_path = os.path.join(self.vault_path, 'In_Progress', 'cloud')
                        os.makedirs(in_progress_path, exist_ok=True)

                        new_path = os.path.join(in_progress_path, filename)
                        os.rename(filepath, new_path)
                        logger.info(f"Moved to In_Progress: {filename}")
                    else:
                        logger.warning(f"Failed to send approval request, will retry")

            except Exception as e:
                logger.error(f"Error processing email task {filename}: {e}")

    def _monitoring_loop(self):
        """Main monitoring loop for cloud agent"""
        logger.info("Starting monitoring loop...")

        while self.running:
            try:
                # Process email triage tasks
                self._process_email_triage()

                # TODO: Process social media draft requests
                # TODO: Process Odoo draft accounting actions
                # TODO: Check for updates from Local agent

                # Sleep before next iteration
                time.sleep(30)  # Check every 30 seconds

            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}")
                time.sleep(60)  # Wait longer on error

    def _health_check_loop(self):
        """Health monitoring loop"""
        while self.running:
            try:
                # Log health status
                logger.info("Health check: Cloud agent running")

                # Check watcher health
                for name, thread in self.watchers:
                    if not thread.is_alive():
                        logger.warning(f"Watcher {name} is not alive!")

                # Check A2A health
                if self.a2a and self.a2a.client:
                    remote_healthy = self.a2a.client.check_remote_health()
                    if remote_healthy:
                        logger.info("✓ Local agent is reachable")
                    else:
                        logger.warning("✗ Local agent is not reachable (may be offline)")

                # Sleep for 5 minutes
                time.sleep(300)

            except Exception as e:
                logger.error(f"Error in health check: {e}")
                time.sleep(300)

    def start(self):
        """Start Platinum Cloud Agent"""
        logger.info("Starting Platinum Cloud Agent...")

        self.running = True

        # Load configuration
        config = self._load_config()

        # Start A2A orchestrator
        self._start_a2a()

        # Start watchers
        self._start_watchers()

        # Start monitoring loop
        monitor_thread = Thread(target=self._monitoring_loop, daemon=True)
        monitor_thread.start()

        # Start health check loop
        health_thread = Thread(target=self._health_check_loop, daemon=True)
        health_thread.start()

        logger.info("=" * 80)
        logger.info("Platinum Cloud Agent Started Successfully")
        logger.info("Mode: Always-On (24/7)")
        logger.info("Responsibilities: Email triage, draft replies, social drafts")
        logger.info("A2A Protocol: Enabled")
        logger.info("=" * 80)

        # Keep running
        try:
            while self.running:
                time.sleep(1)
        except KeyboardInterrupt:
            logger.info("Received shutdown signal")
            self.stop()

    def stop(self):
        """Stop Platinum Cloud Agent"""
        logger.info("Stopping Platinum Cloud Agent...")
        self.running = False

        if self.a2a:
            self.a2a.stop()

        logger.info("Platinum Cloud Agent stopped")


def signal_handler(sig, frame):
    """Handle shutdown signals"""
    logger.info("Received signal to shutdown")
    sys.exit(0)


if __name__ == '__main__':
    # Register signal handlers
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    # Get vault path
    if len(sys.argv) > 1:
        vault_path = sys.argv[1]
    else:
        vault_path = os.path.join(os.path.dirname(__file__), '..')

    vault_path = os.path.abspath(vault_path)

    # Verify vault exists
    if not os.path.exists(vault_path):
        logger.error(f"Vault path does not exist: {vault_path}")
        sys.exit(1)

    # Create and start cloud agent
    agent = PlatinumCloudAgent(vault_path)
    agent.start()
